# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travelagency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('reference', models.TextField()),
            ],
            options={
                'db_table': 'travelagency',
                'managed': False,
            },
        ),
    ]
